# Generated by Django 4.2 on 2023-04-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null='true')),
                ('phone', models.CharField(max_length=200, null='true')),
                ('email', models.CharField(max_length=200, null='true')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
