# Generated by Django 4.2 on 2023-04-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='accounts.product'),
            preserve_default='true',
        ),
    ]
